### ISSUE TITLE
I'm really intrigued!  Do you have any screenshots you can share?

### ISSUE THREAD

**Issue by PySimpleGUI** [cosimg/attritionsim#1]
Your readme is really interesting... the topic is fascinating.... you've got a GUI...

I'm dying to know what it all looks like.   And I think other visitors will be interested too!  It's not typical for a Python program to have a GUI so seeing images will really grab people's attention.

When you get something that's visible, it would be great to drop some screenshots into your readme!  

Was great to stumble onto your project.

![image](https://user-images.githubusercontent.com/46163555/172951990-312336a9-e7c2-4e98-a353-9193fcabdb2f.png)

**Comment by pielstroem** [comment]
Thanks for the hint, I added a screenshot, and a link to PySimpleGui. Keep up the good work - your documentation and tutorials are more than helpful!

**Comment by PySimpleGUI** [comment]
Oh wow!

That's really cool!  Very nice looking graphics.  I didn't know what to expect.

Thank you for  taking the time to add them.
